### ISSUE TITLE
Uncaught error from get_class on array in converter class

### ISSUE THREAD

**Issue by sigveholmen** [zoho/zohocrm-php-sdk-7.0#4]
This issue arises from `get_class` throwing an error if the `$data` variable evaluated on line 85 in `vendor/zohocrm/php-sdk-7.0/src/com/zoho/crm/api/util/Converter.php` is not an object, but an array.

>  get_class(): Argument #1 ($object) must be of type object, array given

This can be reproduced by following the SDK Sample code provided in the readme.

**Comment by raja-k-7453** [comment]
@sigveholmen Thanks for your contribution. Please share the SDK configuration and Sample code and draft an email to [support@zohocrm.com](mailto:support@zohocrm.com). We will follow up on this request, over there.
